2023-04-14 15:10:31,621 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-14 16:56:09,387 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-14 16:56:35,521 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-16 16:34:42,385 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-16 17:04:40,827 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-16 17:09:20,060 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-16 17:31:59,383 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-16 17:38:27,715 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-16 17:40:20,402 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-16 17:41:37,462 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-17 14:36:52,945 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-17 19:25:09,370 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-17 19:25:13,272 ERROR: Exception on /index [GET] [in C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\app\routes.py", line 27, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\VSCode\microblog\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\VSCode\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\VSCode\microblog\app\templates\base.html", line 21, in top-level template code
    <a href="{{ url_for('explor') }}">Explore</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'explor'. Did you mean 'explore' instead?
2023-04-17 19:26:47,807 INFO: Microblog startup [in C:\VSCode\microblog\app\__init__.py:43]
2023-04-17 19:26:50,043 ERROR: Exception on /index [GET] [in C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\app\routes.py", line 27, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\VSCode\microblog\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\VSCode\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\VSCode\microblog\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\app\templates\index.html", line 18, in block 'content'
    {% for post in posts %}
TypeError: 'method' object is not iterable
2023-04-17 19:29:10,285 ERROR: Exception on /index [GET] [in C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\app\routes.py", line 27, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\VSCode\microblog\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\VSCode\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\VSCode\microblog\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VSCode\microblog\app\templates\index.html", line 18, in block 'content'
    {% for post in posts %}
TypeError: 'method' object is not iterable
